const description = 'フロントエンドをそこそこ（?）、バックエンドをちょっと'

const links = [
  { icon: 'logos:github-icon', name: 'GitHub', url: 'https://github.com/tuxsnct' },
  { icon: 'logos:gitlab', name: 'GitLab', url: 'https://gitlab.com/tuxsnct' },
  { icon: 'simple-icons:gitea', name: 'GitLab', url: 'https://git.tuxsnct.com/tuxsnct' },
  { icon: 'fa-brands:keybase', name: 'Keybase', url: 'https://keybase.io/tuxsnct' },
  { icon: 'logos:twitter', name: 'Twitter', url: 'https://twitter.com/tuxsnct' },
  { icon: 'logos:discord-icon', name: 'Discord', url: 'https://discord.com/users/718433564034727976' },
  { icon: 'mdi:email', name: 'Email', url: 'mailto:work@tuxsnct.com' }
]

const projects = [
  { name: 'tuxsnct/www.tuxsnct.com', url: 'https://github.com/tuxsnct/www.tuxsnct.com' },
  { name: 'tuxsnct/blog.tuxsnct.com', url: 'https://github.com/tuxsnct/blog.tuxsnct.com' },
  { name: 'HackU-Kosen-SNCT/webapp', url: 'https://github.com/HackU-Kosen-SNCT/webapp' },
  { name: 'tuxsnct/eslint-config-tuxsnct', url: 'https://github.com/tuxsnct/eslint-config-tuxsnct' },
  { name: 'tuxsnct/leafer-node', url: 'https://github.com/tuxsnct/leafer-node' },
  { name: 'tuxsnct/paddington', url: 'https://github.com/tuxsnct/paddington' },
  { name: 'tuxsnct/shuzo-node', url: 'https://github.com/tuxsnct/shuzo-node' },
  { name: 'tuxsnct/shuzo-go', url: 'https://github.com/tuxsnct/shuzo-go' }
]

const events = [
  { date: '2020', name: '鈴鹿高専 電子情報工学科 入学' },
  { date: '2021/03/03', name: 'NIT TOBA HACKATHON ZTV賞・FIXER賞 受賞' },
  { date: '2021/12/18', name: 'HackU KOSEN ヤフー賞・Happy Hacking賞 受賞' }
]

const skills = [
  { icon: 'logos:archlinux', name: 'Arch Linux' },
  { icon: 'logos:babel', name: 'Babel' },
  { icon: 'logos:bash-icon', name: 'Bash' },
  { icon: 'logos:blitzjs-icon', name: 'Blitz' },
  { icon: 'logos:c-plusplus', name: 'C++' },
  { icon: 'logos:centos-icon', name: 'CentOS' },
  { icon: 'logos:circleci', name: 'CircleCI' },
  { icon: 'logos:nodejs-icon', name: 'Node.js' },
  { icon: 'logos:cloudflare', name: 'Cloudflare' },
  { icon: 'logos:cloudinary', name: 'Cloudinary' },
  { icon: 'logos:create-react-app', name: 'Create React App' },
  { icon: 'logos:css-3', name: 'CSS3' },
  { icon: 'logos:debian', name: 'Debian' },
  { icon: 'logos:docker', name: 'Docker' },
  { icon: 'logos:elasticsearch', name: 'Elasticsearch' },
  { icon: 'logos:electron', name: 'Electron' },
  { icon: 'logos:elm', name: 'Elm' },
  { icon: 'logos:eslint', name: 'ESLint' },
  { icon: 'logos:express', name: 'Express' },
  { icon: 'logos:firebase', name: 'Firebase' },
  { icon: 'logos:flask', name: 'Flask' },
  { icon: 'logos:gatsby', name: 'Gatsby.js' },
  { icon: 'logos:ghost', name: 'Ghost' },
  { icon: 'logos:git-icon', name: 'Git' },
  { icon: 'logos:github-icon', name: 'GitHub' },
  { icon: 'logos:gitlab', name: 'GitLab' },
  { icon: 'logos:go', name: 'Go' },
  { icon: 'logos:graphql', name: 'GraphQL' },
  { icon: 'logos:grunt', name: 'Grunt' },
  { icon: 'logos:gulp', name: 'Gulp' },
  { icon: 'logos:heroku-icon', name: 'Heroku' },
  { icon: 'logos:html-5', name: 'HTML5' },
  { icon: 'logos:intellij-idea', name: 'IntelliJ IDEA' },
  { icon: 'logos:jamstack-icon', name: 'Jamstack' },
  { icon: 'logos:javascript', name: 'JavaScript' },
  { icon: 'logos:jest', name: 'Jest' },
  { icon: 'logos:less', name: 'Less' },
  { icon: 'logos:lighthouse', name: 'Lighthouse' },
  { icon: 'logos:linode', name: 'Linode' },
  { icon: 'logos:linux-tux', name: 'Linux' },
  { icon: 'logos:lua', name: 'Lua' },
  { icon: 'logos:manjaro', name: 'Manjaro' },
  { icon: 'logos:markdown', name: 'Markdown' },
  { icon: 'logos:marko', name: 'Marko' },
  { icon: 'logos:microsoft-azure', name: 'Azure' },
  { icon: 'logos:neovim', name: 'Neovim' },
  { icon: 'logos:netlify', name: 'Netlify' },
  { icon: 'logos:nextjs-icon', name: 'Next.js' },
  { icon: 'logos:nginx', name: 'Nginx' },
  { icon: 'logos:npm-icon', name: 'NPM' },
  { icon: 'logos:parcel-icon', name: 'Parcel' },
  { icon: 'logos:postcss', name: 'PostCSS' },
  { icon: 'logos:preact', name: 'Preact' },
  { icon: 'logos:prettier', name: 'Prettier' },
  { icon: 'logos:puppeteer', name: 'Puppeteer' },
  { icon: 'logos:pwa', name: 'PWA' },
  { icon: 'logos:python', name: 'Python' },
  { icon: 'logos:qt', name: 'Qt' },
  { icon: 'logos:react', name: 'React' },
  { icon: 'logos:react-router', name: 'React Router' },
  { icon: 'logos:redhat-icon', name: 'RHEL' },
  { icon: 'logos:rocky-linux-icon', name: 'Rocky Linux' },
  { icon: 'logos:rollupjs', name: 'Rollup' },
  { icon: 'logos:rome-icon', name: 'Rome' },
  { icon: 'logos:sass', name: 'Sass' },
  { icon: 'logos:solidjs-icon', name: 'Solid' },
  { icon: 'logos:storybook-icon', name: 'Storybook' },
  { icon: 'logos:strapi-icon', name: 'Strapi' },
  { icon: 'logos:stylelint', name: 'Stylelint' },
  { icon: 'logos:stylus', name: 'Stylus' },
  { icon: 'logos:suse', name: 'openSUSE' },
  { icon: 'logos:svelte-icon', name: 'Svelte' },
  { icon: 'logos:swc', name: 'SWC' },
  { icon: 'logos:tailwindcss-icon', name: 'Tailwind CSS' },
  { icon: 'logos:terser-icon', name: 'Terser' },
  { icon: 'logos:travis-ci', name: 'Travis CI' },
  { icon: 'logos:typescript-icon', name: 'TypeScript' },
  { icon: 'logos:ubuntu', name: 'Ubuntu' },
  { icon: 'logos:vim', name: 'Vim' },
  { icon: 'logos:visual-studio-code', name: 'Visual Studio Code' },
  { icon: 'logos:vitejs', name: 'Vite' },
  { icon: 'logos:webpack', name: 'Webpack' },
  { icon: 'logos:wordpress-icon', name: 'WordPress' },
  { icon: 'logos:xampp', name: 'XAMPP' },
  { icon: 'logos:yarn', name: 'Yarn' }
]

export {
  description,
  links,
  projects,
  events,
  skills
}
